[package]
name = "boom-meter"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
rand = "0.9.0"
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
hex = "0.4"

[[bin]]
name = "boom-meter"
path = "main.rs"
